{"asctime": "2025-03-01 11:12:25,639", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/signup/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/signup/'>"}
{"asctime": "2025-03-01 11:12:25,642", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/signup/ HTTP/1.1\" 500 222", "log_type": null, "data": null, "request": "<socket.socket fd=1392, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50879)>", "server_time": "01/Mar/2025 11:12:25", "status_code": 500}
{"asctime": "2025-03-01 11:17:08,065", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/signup/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/signup/'>"}
{"asctime": "2025-03-01 11:17:08,067", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/signup/ HTTP/1.1\" 500 222", "log_type": null, "data": null, "request": "<socket.socket fd=1508, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50935)>", "server_time": "01/Mar/2025 11:17:08", "status_code": 500}
{"asctime": "2025-03-01 11:55:52,361", "levelname": "ERROR", "module": "basehttp", "message": "You're accessing the development server over HTTPS, but it only supports HTTP.", "log_type": null, "data": null, "request": "<socket.socket fd=1444, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51405)>", "server_time": "01/Mar/2025 11:55:52", "status_code": 500}
{"asctime": "2025-03-01 12:16:05,092", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:16:05,093", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 230", "log_type": null, "data": null, "request": "<socket.socket fd=1520, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51883)>", "server_time": "01/Mar/2025 12:16:05", "status_code": 500}
{"asctime": "2025-03-01 12:17:43,764", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:17:43,765", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 210", "log_type": null, "data": null, "request": "<socket.socket fd=1340, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51895)>", "server_time": "01/Mar/2025 12:17:43", "status_code": 500}
{"asctime": "2025-03-01 12:17:43,777", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:17:43,778", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 230", "log_type": null, "data": null, "request": "<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51907)>", "server_time": "01/Mar/2025 12:17:43", "status_code": 500}
{"asctime": "2025-03-01 12:18:43,660", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:18:43,661", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 210", "log_type": null, "data": null, "request": "<socket.socket fd=1264, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51969)>", "server_time": "01/Mar/2025 12:18:43", "status_code": 500}
{"asctime": "2025-03-01 12:18:43,667", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:18:43,668", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 222", "log_type": null, "data": null, "request": "<socket.socket fd=1380, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51968)>", "server_time": "01/Mar/2025 12:18:43", "status_code": 500}
{"asctime": "2025-03-01 12:22:00,397", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:22:00,398", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 192", "log_type": null, "data": null, "request": "<socket.socket fd=1448, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52014)>", "server_time": "01/Mar/2025 12:22:00", "status_code": 500}
{"asctime": "2025-03-01 12:22:43,743", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/verify/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: GET '/api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo'>"}
{"asctime": "2025-03-01 12:22:43,745", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /api/v1/accounts/email/verify/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiZW1haWwiOiJzYW50b3Noam52cm9wYXJAZ21haWwuY29tIiwiZXhwIjoxNzQwODE3NzEwLCJpYXQiOjE3NDA4MTA1MTAsInRva2VuX3R5cGUiOiJlbWFpbF92ZXJpZmljYXRpb24ifQ.H3X-sXlbs5-btbJ2RSJ8KFlcOLCvy48ClT8Eo3zboHo HTTP/1.1\" 500 210", "log_type": null, "data": null, "request": "<socket.socket fd=1440, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52033)>", "server_time": "01/Mar/2025 12:22:43", "status_code": 500}
{"asctime": "2025-03-05 12:57:38,080", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/password/reset/request/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/password/reset/request/'>"}
{"asctime": "2025-03-05 12:57:38,083", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/password/reset/request/ HTTP/1.1\" 500 223", "log_type": null, "data": null, "request": "<socket.socket fd=1328, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50119)>", "server_time": "05/Mar/2025 12:57:38", "status_code": 500}
{"asctime": "2025-03-10 12:39:44,215", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:39:44,219", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 226", "log_type": null, "data": null, "request": "<socket.socket fd=1724, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51357)>", "server_time": "10/Mar/2025 12:39:44", "status_code": 500}
{"asctime": "2025-03-10 12:40:27,670", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:40:27,671", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 219", "log_type": null, "data": null, "request": "<socket.socket fd=1152, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51419)>", "server_time": "10/Mar/2025 12:40:27", "status_code": 500}
{"asctime": "2025-03-10 12:40:43,351", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:40:43,353", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 248", "log_type": null, "data": null, "request": "<socket.socket fd=1188, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51439)>", "server_time": "10/Mar/2025 12:40:43", "status_code": 500}
{"asctime": "2025-03-10 12:41:05,302", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 220, in _get_response\n    response = response.render()\n               ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\response.py\", line 114, in render\n    self.content = self.rendered_content\n                   ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\response.py\", line 74, in rendered_content\n    ret = renderer.render(self.data, accepted_media_type, context)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\renderers.py\", line 100, in render\n    ret = json.dumps(\n          ^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\utils\\json.py\", line 25, in dumps\n    return json.dumps(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\encoder.py\", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\utils\\encoders.py\", line 67, in default\n    return super().default(obj)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type AttributeError is not JSON serializable", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:41:05,327", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 16053", "log_type": null, "data": null, "request": "<socket.socket fd=1216, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51457)>", "server_time": "10/Mar/2025 12:41:05", "status_code": 500}
{"asctime": "2025-03-10 12:41:56,261", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:41:56,263", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 220", "log_type": null, "data": null, "request": "<socket.socket fd=1180, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51547)>", "server_time": "10/Mar/2025 12:41:56", "status_code": 500}
{"asctime": "2025-03-10 12:42:23,811", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:42:23,813", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 218", "log_type": null, "data": null, "request": "<socket.socket fd=1196, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51573)>", "server_time": "10/Mar/2025 12:42:23", "status_code": 500}
{"asctime": "2025-03-10 12:43:56,688", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:43:56,690", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1220, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51757)>", "server_time": "10/Mar/2025 12:43:56", "status_code": 500}
{"asctime": "2025-03-10 12:44:46,956", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:44:46,960", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1500, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51853)>", "server_time": "10/Mar/2025 12:44:46", "status_code": 500}
{"asctime": "2025-03-10 12:48:10,136", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:48:10,138", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=740, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52238)>", "server_time": "10/Mar/2025 12:48:10", "status_code": 500}
{"asctime": "2025-03-10 12:49:15,179", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:49:15,179", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1152, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52328)>", "server_time": "10/Mar/2025 12:49:15", "status_code": 500}
{"asctime": "2025-03-10 12:50:36,628", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:50:36,630", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1144, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52450)>", "server_time": "10/Mar/2025 12:50:36", "status_code": 500}
{"asctime": "2025-03-10 12:51:03,078", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:51:03,080", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1148, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52488)>", "server_time": "10/Mar/2025 12:51:03", "status_code": 500}
{"asctime": "2025-03-10 12:51:13,462", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:51:13,464", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1468, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52495)>", "server_time": "10/Mar/2025 12:51:13", "status_code": 500}
{"asctime": "2025-03-10 12:52:00,024", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:52:00,026", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1160, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52633)>", "server_time": "10/Mar/2025 12:52:00", "status_code": 500}
{"asctime": "2025-03-10 12:52:26,454", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:52:26,454", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1176, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52671)>", "server_time": "10/Mar/2025 12:52:26", "status_code": 500}
{"asctime": "2025-03-10 12:53:05,456", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:53:05,456", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=1176, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52789)>", "server_time": "10/Mar/2025 12:53:05", "status_code": 500}
{"asctime": "2025-03-10 12:53:23,746", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/orders/place/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/orders/place/'>"}
{"asctime": "2025-03-10 12:53:23,748", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/orders/place/ HTTP/1.1\" 500 150", "log_type": null, "data": null, "request": "<socket.socket fd=660, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 52800)>", "server_time": "10/Mar/2025 12:53:23", "status_code": 500}
{"asctime": "2025-03-14 13:29:34,550", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/send/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/email/send/'>"}
{"asctime": "2025-03-14 13:29:34,553", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/email/send/ HTTP/1.1\" 500 242", "log_type": null, "data": null, "request": "<socket.socket fd=968, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51209)>", "server_time": "14/Mar/2025 13:29:34", "status_code": 500}
{"asctime": "2025-03-14 13:29:35,932", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/email/send/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/email/send/'>"}
{"asctime": "2025-03-14 13:29:35,933", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/email/send/ HTTP/1.1\" 500 248", "log_type": null, "data": null, "request": "<socket.socket fd=968, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 51209)>", "server_time": "14/Mar/2025 13:29:35", "status_code": 500}
{"asctime": "2025-03-16 15:23:24,449", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /admin/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 220, in _get_response\n    response = response.render()\n               ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\response.py\", line 114, in render\n    self.content = self.rendered_content\n                   ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\response.py\", line 92, in rendered_content\n    return template.render(context, self._request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\backends\\django.py\", line 107, in render\n    return self.template.render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 171, in render\n    return self._render(context)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 969, in render_annotated\n    return self.render(context)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 969, in render_annotated\n    return self.render(context)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 969, in render_annotated\n    return self.render(context)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\defaulttags.py\", line 327, in render\n    return nodelist.render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 969, in render_annotated\n    return self.render(context)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\defaulttags.py\", line 327, in render\n    return nodelist.render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\base.py\", line 969, in render_annotated\n    return self.render(context)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\template\\defaulttags.py\", line 480, in render\n    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\urls\\base.py\", line 88, in reverse\n    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 831, in _reverse_with_prefix\n    raise NoReverseMatch(msg)\ndjango.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.", "status_code": 500, "request": "<WSGIRequest: GET '/admin/'>"}
{"asctime": "2025-03-16 15:23:24,470", "levelname": "ERROR", "module": "basehttp", "message": "\"GET /admin/ HTTP/1.1\" 500 27891", "log_type": null, "data": null, "request": "<socket.socket fd=1260, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 53996)>", "server_time": "16/Mar/2025 15:23:24", "status_code": 500}
{"asctime": "2025-03-20 17:16:29,039", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py\", line 354, in execute\n    return super().execute(query, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such table: contact_contactmessage\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 17, in post\n    serializer.save()\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\serializers.py\", line 208, in save\n    self.instance = self.create(validated_data)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\serializers.py\", line 989, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 679, in create\n    obj.save(force_insert=True, using=self.db)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 892, in save\n    self.save_base(\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 998, in save_base\n    updated = self._save_table(\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 1161, in _save_table\n    results = self._do_insert(\n              ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 1202, in _do_insert\n    return manager._insert(\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1847, in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\compiler.py\", line 1836, in execute_sql\n    cursor.execute(sql, params)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py\", line 354, in execute\n    return super().execute(query, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such table: contact_contactmessage", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:16:29,053", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 23693", "log_type": null, "data": null, "request": "<socket.socket fd=1188, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49829)>", "server_time": "20/Mar/2025 17:16:29", "status_code": 500}
{"asctime": "2025-03-20 17:16:52,163", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py\", line 354, in execute\n    return super().execute(query, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such table: contact_contactmessage\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 17, in post\n    serializer.save()\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\serializers.py\", line 208, in save\n    self.instance = self.create(validated_data)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\serializers.py\", line 989, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 679, in create\n    obj.save(force_insert=True, using=self.db)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 892, in save\n    self.save_base(\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 998, in save_base\n    updated = self._save_table(\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 1161, in _save_table\n    results = self._do_insert(\n              ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 1202, in _do_insert\n    return manager._insert(\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1847, in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\compiler.py\", line 1836, in execute_sql\n    cursor.execute(sql, params)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py\", line 354, in execute\n    return super().execute(query, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such table: contact_contactmessage", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:16:52,173", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 23694", "log_type": null, "data": null, "request": "<socket.socket fd=1188, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49829)>", "server_time": "20/Mar/2025 17:16:52", "status_code": 500}
{"asctime": "2025-03-20 17:17:48,984", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 22, in post\n    code=SC.REQ_DATA_CREATED.value,\n         ^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'SuccessCodes' has no attribute 'REQ_DATA_CREATED'. Did you mean: 'REQ_DATA_RETRIEVED'?", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:17:48,992", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 15701", "log_type": null, "data": null, "request": "<socket.socket fd=1108, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49879)>", "server_time": "20/Mar/2025 17:17:48", "status_code": 500}
{"asctime": "2025-03-20 17:17:53,696", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 22, in post\n    code=SC.REQ_DATA_CREATED.value,\n         ^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'SuccessCodes' has no attribute 'REQ_DATA_CREATED'. Did you mean: 'REQ_DATA_RETRIEVED'?", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:17:53,705", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 15774", "log_type": null, "data": null, "request": "<socket.socket fd=1108, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49879)>", "server_time": "20/Mar/2025 17:17:53", "status_code": 500}
{"asctime": "2025-03-20 17:18:38,559", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 22, in post\n    code=SC.REQ_DATA_CREATED.value,\n         ^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'SuccessCodes' has no attribute 'REQ_DATA_CREATED'. Did you mean: 'REQ_DATA_RETRIEVED'?", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:18:38,569", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 15773", "log_type": null, "data": null, "request": "<socket.socket fd=912, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49926)>", "server_time": "20/Mar/2025 17:18:38", "status_code": 500}
{"asctime": "2025-03-20 17:19:29,012", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 22, in post\n    code=SC.REQ_DATA_CREATED.value,\n         ^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'SuccessCodes' has no attribute 'REQ_DATA_CREATED'. Did you mean: 'REQ_DATA_RETRIEVED'?", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:19:29,023", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 15729", "log_type": null, "data": null, "request": "<socket.socket fd=888, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 49987)>", "server_time": "20/Mar/2025 17:19:29", "status_code": 500}
{"asctime": "2025-03-20 17:19:55,525", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/contact/submit/", "log_type": null, "data": null, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\santosh\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\boss-backend--l-lEIM2-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"V:\\Code PlayGround\\boss-ecommerce\\backend\\contact\\views.py\", line 22, in post\n    code=SC.REQ_DATA_CREATED.value,\n         ^^^^^^^^^^^^^^^^^^^\nAttributeError: type object 'SuccessCodes' has no attribute 'REQ_DATA_CREATED'. Did you mean: 'REQ_DATA_RETRIEVED'?", "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/contact/submit/'>"}
{"asctime": "2025-03-20 17:19:55,535", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/contact/submit/ HTTP/1.1\" 500 15714", "log_type": null, "data": null, "request": "<socket.socket fd=1124, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 50077)>", "server_time": "20/Mar/2025 17:19:55", "status_code": 500}
{"asctime": "2025-04-10 12:25:53,229", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/password/reset/verify-token/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/password/reset/verify-token/'>"}
{"asctime": "2025-04-10 12:25:53,229", "levelname": "ERROR", "module": "log", "message": "Internal Server Error: /api/v1/accounts/password/reset/verify-token/", "log_type": null, "data": null, "status_code": 500, "request": "<WSGIRequest: POST '/api/v1/accounts/password/reset/verify-token/'>"}
{"asctime": "2025-04-10 12:25:53,234", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/password/reset/verify-token/ HTTP/1.1\" 500 204", "log_type": null, "data": null, "request": "<socket.socket fd=1520, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 55099)>", "server_time": "10/Apr/2025 12:25:53", "status_code": 500}
{"asctime": "2025-04-10 12:25:53,234", "levelname": "ERROR", "module": "basehttp", "message": "\"POST /api/v1/accounts/password/reset/verify-token/ HTTP/1.1\" 500 220", "log_type": null, "data": null, "request": "<socket.socket fd=1256, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 55100)>", "server_time": "10/Apr/2025 12:25:53", "status_code": 500}
